services:
  api:
    build:
      context: ./api
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - BASE_URL=https://echo-serv.tbxnet.com
      - API_KEY=aSuperSecretKey

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    environment:
      - API_URL=http://localhost:3001
    depends_on:
      - api
